package com.frontline.offline;

/** Offline content rows: stable key, exact English literal, Indonesian, Hindi. */
public final class LocalizationContent {
    private LocalizationContent() {}

    public static final String[][] ROWS = {
        {"sector.0.name", "First Contact", "Kontak Pertama", "पहला संपर्क"},
        {"sector.1.name", "The Crossing", "Penyeberangan", "पारगमन"},
        {"sector.2.name", "Three Fronts", "Tiga Medan", "तीन मोर्चे"},
        {"sector.3.name", "Broken Coast", "Pantai Terpecah", "टूटा तट"},
        {"sector.4.name", "Crossfire", "Tembak Silang", "दोतरफ़ा प्रहार"},
        {"sector.5.name", "Last Stand", "Pertahanan Akhir", "अंतिम प्रतिरोध"},
        {"sector.6.name", "Foundry Road", "Jalan Peleburan", "ढलाई मार्ग"},
        {"sector.7.name", "Ashen Fields", "Padang Abu", "राख के मैदान"},
        {"sector.8.name", "Split Province", "Provinsi Terbelah", "बँटा प्रांत"},
        {"sector.9.name", "Redwater Basin", "Cekungan Air Merah", "लाल जल घाटी"},
        {"sector.10.name", "Smelter Ring", "Cincin Peleburan", "भट्ठी घेरा"},
        {"sector.11.name", "Voss Hold", "Benteng Voss", "वॉस का गढ़"},
        {"sector.12.name", "Gilded Approach", "Jalan Emas", "स्वर्ण पथ"},
        {"sector.13.name", "Twin Bridges", "Jembatan Kembar", "जुड़वाँ पुल"},
        {"sector.14.name", "Goldwind Reach", "Wilayah Angin Emas", "स्वर्ण पवन क्षेत्र"},
        {"sector.15.name", "Mirror Provinces", "Provinsi Cermin", "दर्पण प्रांत"},
        {"sector.16.name", "League Causeway", "Jalan Serikat", "संघ का सेतु"},
        {"sector.17.name", "Sol Citadel", "Benteng Sol", "सोल दुर्ग"},
        {"sector.18.name", "Veiled Shore", "Pantai Tersamar", "ढका तट"},
        {"sector.19.name", "Northern Signal", "Sinyal Utara", "उत्तरी संकेत"},
        {"sector.20.name", "Obsidian Passage", "Jalur Obsidian", "काली शिला पथ"},
        {"sector.21.name", "Shattered March", "Batas Pecah", "खंडित सीमा"},
        {"sector.22.name", "Nightfall Circuit", "Jalur Senja", "सांझ घेरा"},
        {"sector.23.name", "Veil Bastion", "Benteng Veil", "वेल का गढ़"},
        {"sector.24.name", "Broken Accord", "Pakta Retak", "टूटी संधि"},
        {"sector.25.name", "Three Banners", "Tiga Panji", "तीन ध्वज"},
        {"sector.26.name", "Iron Meridian", "Meridian Besi", "लौह मध्यरेखा"},
        {"sector.27.name", "Fractured Throne", "Takhta Retak", "खंडित सिंहासन"},
        {"sector.28.name", "Last Convergence", "Pertemuan Akhir", "अंतिम संगम"},
        {"sector.29.name", "Concord Citadel", "Benteng Damai", "सहमति दुर्ग"},
        {"sector.30.name", "Western Passage", "Jalur Barat", "पश्चिमी मार्ग"},
        {"sector.31.name", "Ironwater Coast", "Pantai Air Besi", "लौह जल तट"},
        {"sector.32.name", "Rivet Provinces", "Tanah Paku Keling", "कील प्रांत"},
        {"sector.33.name", "Steel Causeway", "Jalan Baja", "इस्पात सेतु"},
        {"sector.34.name", "Dominion Ring", "Cincin Kekuasaan", "राज्य घेरा"},
        {"sector.35.name", "Soren Fortress", "Benteng Soren", "सोरेन दुर्ग"},
        {"sector.36.name", "Frostline Landing", "Pendaratan Es", "हिम अवतरण"},
        {"sector.37.name", "Whitewater Reach", "Wilayah Jeram", "झागदार जल क्षेत्र"},
        {"sector.38.name", "Frozen Channels", "Kanal Beku", "जमी नहरें"},
        {"sector.39.name", "Glacier Divide", "Belahan Gletser", "हिमनद विभाजन"},
        {"sector.40.name", "Icebound Circuit", "Jalur Beku", "हिम घेरा"},
        {"sector.41.name", "Kestrel Anchorage", "Labuhan Kestrel", "केस्ट्रल लंगरगाह"},
        {"sector.42.name", "Broken Coalition", "Koalisi Retak", "खंडित गठबंधन"},
        {"sector.43.name", "Five Banners", "Lima Panji", "पाँच ध्वज"},
        {"sector.44.name", "Cinder and Steel", "Bara dan Baja", "अंगार और इस्पात"},
        {"sector.45.name", "Scattered Oaths", "Sumpah Tercerai", "बिखरी शपथें"},
        {"sector.46.name", "Fivefold Siege", "Kepungan Lima", "पाँचतरफ़ा घेरा"},
        {"sector.47.name", "Coalition Keep", "Benteng Koalisi", "गठबंधन दुर्ग"},
        {"sector.48.name", "Throne Road", "Jalan Takhta", "सिंहासन मार्ग"},
        {"sector.49.name", "Royal Meridian", "Meridian Raja", "शाही मध्यरेखा"},
        {"sector.50.name", "Crown Crossroads", "Simpang Mahkota", "मुकुट चौराहा"},
        {"sector.51.name", "Kings of the Divide", "Raja Pembatas", "विभाजन के राजा"},
        {"sector.52.name", "Four Crown Summit", "Puncak Empat Mahkota", "चार मुकुट शिखर"},
        {"sector.53.name", "Sovereign Bastion", "Benteng Penguasa", "सम्राट का गढ़"},
        {"sector.54.name", "Horizon's Edge", "Tepi Cakrawala", "क्षितिज छोर"},
        {"sector.55.name", "The Long Frontier", "Perbatasan Panjang", "लंबी सीमा"},
        {"sector.56.name", "Alliance Bridge", "Jembatan Aliansi", "गठबंधन सेतु"},
        {"sector.57.name", "Final Assembly", "Himpunan Akhir", "अंतिम सभा"},
        {"sector.58.name", "Beyond the Accord", "Melampaui Pakta", "संधि के पार"},
        {"sector.59.name", "United Citadel", "Benteng Bersatu", "एकजुट दुर्ग"},

        {"chapter.0.name", "Border Sparks", "Percikan Batas", "सीमा की चिंगारी"},
        {"chapter.0.first", "The Ember Pact crosses the frontier.", "Pakta Bara melintasi perbatasan.", "अंगार संधि सीमा पार करती है।"},
        {"chapter.0.second", "Hold the border as rival banners appear.", "Jaga batas saat panji lawan muncul.", "शत्रु ध्वज दिखें तो सीमा थामें।"},
        {"chapter.1.name", "Ember Reach", "Wilayah Bara", "अंगार क्षेत्र"},
        {"chapter.1.first", "The southern foundries answer to Kael Voss.", "Peleburan selatan di bawah Kael Voss.", "दक्षिण की भट्ठियाँ केल वॉस के अधीन हैं।"},
        {"chapter.1.second", "Break the Pact's hold on the Ember Reach.", "Bebaskan Wilayah Bara dari pakta.", "अंगार क्षेत्र से संधि का कब्ज़ा हटाएँ।"},
        {"chapter.2.name", "Auric Divide", "Belahan Emas", "स्वर्ण विभाजन"},
        {"chapter.2.first", "Mira Sol claims the eastern provinces.", "Mira Sol mengklaim provinsi timur.", "मीरा सोल का पूर्वी प्रांतों पर दावा है।"},
        {"chapter.2.second", "Reclaim the divided lands of the Auric League.", "Rebut tanah terbelah Serikat Emas.", "स्वर्ण संघ की बँटी भूमि वापस लें।"},
        {"chapter.3.name", "Vesper Veil", "Tirai Senja", "संध्या आवरण"},
        {"chapter.3.first", "Ilyra Veil rules the northern outposts.", "Ilyra Veil menguasai pos utara.", "उत्तरी चौकियाँ इलिरा वेल के अधीन हैं।"},
        {"chapter.3.second", "Unite the scattered provinces of Vesper.", "Satukan provinsi Senja yang tercerai.", "संध्या के बिखरे प्रांत जोड़ें।"},
        {"chapter.4.name", "Last Accord", "Pakta Terakhir", "अंतिम संधि"},
        {"chapter.4.first", "Three rulers contest the last stronghold.", "Tiga penguasa berebut benteng terakhir.", "तीन शासक अंतिम गढ़ के लिए लड़ते हैं।"},
        {"chapter.4.second", "Reunite your homeland before crossing the sea.", "Satukan negeri sebelum melintasi laut.", "समुद्र पार करने से पहले देश जोड़ें।"},
        {"chapter.5.name", "Iron Frontier", "Batas Besi", "लौह सीमा"},
        {"chapter.5.first", "Rhea Soren guards the western steel coast.", "Rhea Soren menjaga pantai baja barat.", "रिया सोरेन पश्चिम का इस्पात तट बचाती हैं।"},
        {"chapter.5.second", "Challenge the Dominion and its rival rulers.", "Tantang Besi dan penguasa lawan.", "लौह राज्य और शत्रु शासकों को चुनौती दें।"},
        {"chapter.6.name", "Frost March", "Batas Es", "हिम सीमा"},
        {"chapter.6.first", "Nara Kestrel commands the icebound channels.", "Nara Kestrel menguasai kanal beku.", "जमी नहरें नारा केस्ट्रल के अधीन हैं।"},
        {"chapter.6.second", "Five rival banners contest a wider frontier.", "Lima panji berebut perbatasan luas.", "पाँच ध्वज विस्तृत सीमा पर भिड़ते हैं।"},
        {"chapter.7.name", "Shattered Coalition", "Koalisi Pecah", "टूटा गठबंधन"},
        {"chapter.7.first", "Old enemies unite behind the Iron Dominion.", "Musuh lama bersatu di bawah Besi.", "पुराने शत्रु लौह राज्य के साथ जुटे हैं।"},
        {"chapter.7.second", "Break their coalition, one stronghold at a time.", "Patahkan koalisi, benteng demi benteng.", "एक-एक गढ़ जीतकर गठबंधन तोड़ें।"},
        {"chapter.8.name", "King's Gambit", "Gambit Raja", "राजा की चाल"},
        {"chapter.8.first", "The Frost Union bargains for every crown.", "Persatuan Es menawar setiap mahkota.", "हिम संघ हर मुकुट के लिए सौदा करता है।"},
        {"chapter.8.second", "Hold four enemy kings to turn the campaign.", "Kuasai empat raja untuk membalik perang.", "चार शत्रु राजा लेकर अभियान पलटें।"},
        {"chapter.9.name", "United Horizon", "Cakrawala Bersatu", "एकजुट क्षितिज"},
        {"chapter.9.first", "All five rulers gather beyond the Accord.", "Lima penguasa berkumpul di luar Pakta.", "पाँचों शासक संधि के पार जुटे हैं।"},
        {"chapter.9.second", "Secure the final citadel and unite the frontier.", "Rebut benteng akhir, satukan perbatasan.", "अंतिम दुर्ग जीतें और सीमा एकजुट करें।"},

        {"faction.0.name", "Frontier Alliance", "Aliansi Perbatasan", "सीमा गठबंधन"},
        {"faction.0.short", "YOU", "ANDA", "आप"},
        {"faction.0.ruler", "Frontier Council", "Dewan Perbatasan", "सीमा परिषद"},
        {"faction.1.name", "Ember Pact", "Pakta Bara", "अंगार संधि"},
        {"faction.1.short", "Ember", "Bara", "अंगार"},
        {"faction.1.ruler", "Marshal Kael Voss", "Marsekal Kael Voss", "मार्शल केल वॉस"},
        {"faction.2.name", "Auric League", "Serikat Emas", "स्वर्ण संघ"},
        {"faction.2.short", "Auric", "Emas", "स्वर्ण"},
        {"faction.2.ruler", "Chancellor Mira Sol", "Kanselir Mira Sol", "चांसलर मीरा सोल"},
        {"faction.3.name", "Vesper Order", "Ordo Senja", "संध्या दल"},
        {"faction.3.short", "Vesper", "Senja", "संध्या"},
        {"faction.3.ruler", "Warden Ilyra Veil", "Penjaga Ilyra Veil", "प्रहरी इलिरा वेल"},
        {"faction.4.name", "Iron Dominion", "Kekuasaan Besi", "लौह राज्य"},
        {"faction.4.short", "Iron", "Besi", "लौह"},
        {"faction.4.ruler", "General Rhea Soren", "Jenderal Rhea Soren", "जनरल रिया सोरेन"},
        {"faction.5.name", "Frost Union", "Persatuan Es", "हिम संघ"},
        {"faction.5.short", "Frost", "Es", "हिम"},
        {"faction.5.ruler", "Admiral Nara Kestrel", "Laksamana Nara Kestrel", "एडमिरल नारा केस्ट्रल"},

        {"mission.0.name", "Crown Watch", "Jaga Mahkota", "मुकुट पहरा"},
        {"mission.1.name", "Three Front Watch", "Jaga Tiga Medan", "तीन मोर्चों का पहरा"},
        {"mission.2.name", "Gilded Watch", "Jaga Emas", "स्वर्ण पहरा"},
        {"mission.3.name", "Home Guard", "Penjaga Negeri", "घर की रक्षा"},
        {"mission.4.name", "Province Guard", "Penjaga Provinsi", "प्रांत रक्षा"},
        {"mission.5.name", "Veiled Guard", "Penjaga Tirai", "आवरण रक्षा"},
        {"mission.6.name", "Lean Frontier", "Batas Hemat", "कम खर्च सीमा"},
        {"mission.7.name", "Lean Three Fronts", "Tiga Medan Hemat", "कम खर्च तीन मोर्चे"},
        {"mission.8.name", "Lean Gilded Front", "Medan Emas Hemat", "कम खर्च स्वर्ण मोर्चा"}
    };
}
